CarApp.Mvc/Controllers/CarController.cs
using System;
using System.Web.Mvc;
using CarApp.Domain;
using CarApp.Domain.Entities;
using System.Linq;

namespace CarApp.Mvc.Controllers
{
    public class CarController : Controller
    {
        private readonly Func<IEntityAccess<Car>> _carAccess;
        private readonly Func<IEntityAccess<Site>> _siteAccess;

        public CarController(Func<IEntityAccess<Car>> carAccess, Func<IEntityAccess<Site>> siteAccess)
        {
            _carAccess = carAccess;
            _siteAccess = siteAccess;
        }

        public ActionResult Index()
        {
            var cars = _carAccess().List();

            return View(cars);
        }

        public ActionResult Details(Guid id)
        {
            var model = _carAccess().Get(id);

            return View(model);
        }

        public ActionResult Create()
        {
            Car model = new Car();


            return View(model);

        }

        [HttpPost]

        public ActionResult Create(Car model)
        {
            if (!ModelState.IsValid || model.LicencePlate == null)
                return View(model);

            _carAccess().Save(model);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(Guid? id)
        {

            Car model = _carAccess().Get(id.Value);
            TelephelyekLista();

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Car model)
        {
            if (!ModelState.IsValid || model.LicencePlate == null)
                return View(model);

            _carAccess().Update(model);


            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult Delete(Guid id)
        {
            _carAccess().Delete(id);

            return new JsonResult() { Data = new { success = true }, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        private void TelephelyekLista()
        {
            ViewBag.Telephelyek = _siteAccess().List().Select(y => new SelectListItem { Text = y.Address, Value = y.Id.ToString() });
        }
    }
}

CarApp.Mvc/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarApp.Mvc.Controllers
{
    public class DefaultController : Controller
    {
        //
        // GET: /Default/

        public ActionResult Index()
        {
            return View();
        }

    }
}

CarApp.Mvc/Controllers/DesignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarApp.Mvc.Controllers
{
    public class DesignController : Controller
    {
        //
        // GET: /Design/

        public ActionResult Index()
        {
            return View();
        }

    }
}

CarApp.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarAppUIMvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index() 
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CarApp.Mvc/Controllers/SiteController.cs
using CarApp.Domain;
using CarApp.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarApp.Mvc.Controllers
{
    public class SiteController : Controller
    {
        private readonly Func<IEntityAccess<Site>> _siteAccess;

        public SiteController(Func<IEntityAccess<Site>> siteAccess)
        {
            _siteAccess = siteAccess;
        }

        public ActionResult Index()
        {
            var sites = _siteAccess().List();
            return View(sites);
        }

        public ActionResult Details(Guid id)
        {
            var sites = _siteAccess().Get(id);
            return View(sites);
        }

        public ActionResult Create()
        {
            Site sites = new Site();

            return View(sites);
        }

        [HttpPost]
        public ActionResult Create(Site model)
        {
            if (!ModelState.IsValid || model.ZipCode == null)
                return View(model);

            _siteAccess().Save(model);

            return RedirectToAction("Index");
        }


        public ActionResult Edit(Guid id)
        {
            var site = _siteAccess().Get(id);
            return View(site);
        }

        [HttpPost]
        public ActionResult Edit(Site model)
        {
            if (!ModelState.IsValid || model.ZipCode == null || model.ZipCode == "")
                return View(model);

            _siteAccess().Update(model);
            return RedirectToAction("Index");

        }

        [HttpPost]
        public JsonResult Delete(Guid id)
        {
            _siteAccess().Delete(id);

            return new JsonResult() { Data = new { success = true }, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

    }
}

CarApp.Mvc/Views/Car/Create.cshtml
@model CarApp.Domain.Entities.Car


@{
    ViewBag.Title = "Új autó felvétele";
}

<style>
    div {
        margin: 0 0 10px 5px;
    }

    h2 {
        margin-bottom: 20px;
    }
</style>

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    <div>
        @Html.HiddenFor(x => x.Id)
        Licence Plate : @Html.EditorFor(x => x.LicencePlate)

    </div>
    <button type="submit">Mentés</button>
}


<div>
    <a href="@Url.Action("Index")">Vissza</a>
</div>

CarApp.Mvc/Views/Car/Details.cshtml
@model CarApp.Domain.Entities.Car


@{
    ViewBag.Title = "Megtekintés";
}

<style>
    div {
        margin: 0 0 10px 5px;
    }
    h2 {
        margin-bottom: 20px;
    }
</style>

<h2>@ViewBag.Title</h2>


<div>
    Licence Plate : @Model.LicencePlate

</div>
<div>
    <a href="@Url.Action("Index")">Vissza</a>
    <a href="@Url.Action("Edit", new { id = Model.Id })">Szerkesztés</a>
</div>


CarApp.Mvc/Views/Car/Edit.cshtml
@model CarApp.Domain.Entities.Car


@{
    ViewBag.Title = "Szerkesztés";
}

<style>
    div {
        margin: 0 0 10px 5px;
    }

    h2 {
        margin-bottom: 20px;
    }
</style>

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    <div>
        @Html.HiddenFor(x => x.Id)
        Licence Plate : @Html.EditorFor(x => x.LicencePlate)
        Telephely: @Html.DropDownListFor(x => x.TelepId, (IEnumerable<SelectListItem>) ViewBag.Telephelyek)

    </div>
    <button type="submit">Mentés</button>
}


<div>
    <a href="@Url.Action("Index")">Vissza</a>
</div>


CarApp.Mvc/Views/Car/Index.cshtml
@model IEnumerable<CarApp.Domain.Entities.Car>

@{
    ViewBag.Title = "Cars";
}

<h2>@ViewBag.Title</h2>

<table>
    <thead>
        <tr>
            <th>
                Licence plate
            </th>
            <th>
                Telephely
            </th>
            <th>
                Műveletek
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var car in Model)
        {
            <tr>
                <td>
                    @car.LicencePlate
                </td>
                <td>
                    @car.TelepHelyAddress
                </td>
                <td>
                    @Html.ActionLink("részletek", "Details", new { id = car.Id })
                    @Html.ActionLink("szerkesztés", "Edit", new { id = car.Id })
                    @Html.ActionLink("törlés", "Delete", new { id = car.Id }, new { @class = "DeleteLink" })
                </td>
            </tr>
        }

    </tbody>
</table>

@Html.ActionLink("új autó", "Create")

@section scripts {


  <script src="@Url.Content("/Scripts/deletelink.js")" type="text/javascript">
        

    </script>
}


CarApp.Mvc/Views/Default/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="@Url.Content("~/Content/Index.css")" rel="stylesheet" type="text/css"/>
</head>
<body>
    <div>
        <div class="header">
            <div class="leftButton">
                  &nbsp;
            </div>
        </div>
       <p>
           dfghdgfhgdf v trr rdstzrzt rdst rzrdet
       </p> 
        <p>dzhtdfzh
        dthdtfh
        dtfhdfghghjgfjhgfj
        jhgjhfgjhfjhfj</p>
    </div>
</body>
</html>

CarApp.Mvc/Views/Design/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="@Url.Content("~/Content/Index.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <div>
        
    </div>
</body>
</html>

CarApp.Mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

CarApp.Mvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

CarApp.Mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                To learn more about ASP.NET MVC visit
                <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>.
                The page features <mark>videos, tutorials, and samples</mark> to help you get the most from ASP.NET MVC.
                If you have any questions about ASP.NET MVC visit
                <a href="http://forums.asp.net/1146.aspx/1?MVC" title="ASP.NET MVC Forum">our forums</a>.
            </p>
        </div>
    </section>
}
<h3>We suggest the following:</h3>
<ol class="round">
    <li class="one">
        <h5>Getting Started</h5>
        ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
        enables a clean separation of concerns and that gives you full control over markup
        for enjoyable, agile development. ASP.NET MVC includes many features that enable
        fast, TDD-friendly development for creating sophisticated applications that use
        the latest web standards.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245151">Learn more…</a>
    </li>

    <li class="two">
        <h5>Add NuGet packages and jump-start your coding</h5>
        NuGet makes it easy to install and update free libraries and tools.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245153">Learn more…</a>
    </li>

    <li class="three">
        <h5>Find Web Hosting</h5>
        You can easily find a web hosting company that offers the right mix of features
        and price for your applications.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245157">Learn more…</a>
    </li>
</ol>

CarApp.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @RenderSection("styles", false)
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                       Hello, <span class="username">@User.Identity.Name</span>!
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Sites", "Index", "Site")</li>
                            <li>@Html.ActionLink("Cars", "Index", "Car")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

CarApp.Mvc/Views/Site/Create.cshtml
@model CarApp.Domain.Entities.Site

@{
    ViewBag.Title = "Új teelp felvétele";
}

<style>
    div {
        margin: 0 0 10px 5px;
    }

    h2 {
        margin-bottom: 20px;
    }
</style>

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    <div>
        @Html.HiddenFor(x => x.Id)
        Zip Code : @Html.EditorFor(x => x.ZipCode)
        Address : @Html.EditorFor(x => x.Address)

    </div>
    <button type="submit">Mentés</button>
}


<div>
    <a href="@Url.Action("Index")">Vissza</a>
</div>

CarApp.Mvc/Views/Site/Details.cshtml
@model CarApp.Domain.Entities.Site


@{
    ViewBag.Title = "Megtekintés";
}

<style>
    div {
        margin: 0 0 10px 5px;
    }

    h2 {
        margin-bottom: 20px;
    }
</style>

<h2>@ViewBag.Title</h2>


<div>
    Zip Code = @Model.ZipCode
    Address = @Model.Address

</div>
<div>
    <a href="@Url.Action("Index")">Vissza</a>
    <a href="@Url.Action("Edit", new { id = Model.Id })">Szerkesztés</a>
</div>

CarApp.Mvc/Views/Site/Edit.cshtml
@model CarApp.Domain.Entities.Site

@{
    ViewBag.Title = "Telep mód.";
}

<style>
    div {
        margin: 0 0 10px 5px;
    }

    h2 {
        margin-bottom: 20px;
    }
</style>

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    <div>
        @Html.HiddenFor(x => x.Id)
        Zip Code : @Html.EditorFor(x => x.ZipCode)
        Address : @Html.EditorFor(x => x.Address)

    </div>
    <button type="submit">Mentés</button>
}


<div>
    <a href="@Url.Action("Index")">Vissza</a>
</div>

CarApp.Mvc/Views/Site/Index.cshtml
@model IEnumerable<CarApp.Domain.Entities.Site>

@{
    ViewBag.Title = "Sites";
}

<h2>@ViewBag.Title</h2>

<table>
    <thead>
        <tr>
            <th>
                Zip Code
            </th>
            <th>
                Address
            </th>
            <th>
                Műveletek
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var site in Model)
        {
            <tr>
                <td>
                    @site.ZipCode
                </td>
                <td>
                    @site.Address
                </td>
                <td>
                    @Html.ActionLink("részletek", "Details", new { id = site.Id })
                    @Html.ActionLink("szerkesztés", "Edit", new { id = site.Id })
                    @Html.ActionLink("törlés", "Delete", new { id = site.Id }, new { @class = "DeleteLink" })
                </td>
            </tr>
        }

    </tbody>
</table>

@Html.ActionLink("Új site", "Create")

@section scripts {


    <script src="@Url.Content("/Scripts/deletelink.js")" type="text/javascript">


    </script>
}